### ISSUE TITLE
Feature request: transformer "timestamp with time zone"

### ISSUE THREAD

**Issue by TCY16** [GreenmaskIO/greenmask#131]
Hi!

I'm not 100% sure if this already exists or is possible, but it would be very useful to have a transformer for the column type `TIMESTAMP WITH TIME ZONE`. Would this be possible?

Thanks!

**Comment by wwoytenko** [comment]
Hi! 

It already exists. Just use [RandomDate](https://greenmask.io/latest/built_in_transformers/standard_transformers/random_date/) or [NoiseDate](https://greenmask.io/latest/built_in_transformers/standard_transformers/noise_date/).

Check the supported `Supported DB types` column in parameters table

<img width="830" alt="image" src="https://github.com/GreenmaskIO/greenmask/assets/74241416/117e96c5-4b42-4eb6-8480-06c94718aa0f">

**Comment by TCY16** [comment]
Great! Thanks for lightning quick reply as always 😄
