### ISSUE TITLE
Delete old dumps except for the last X

### ISSUE THREAD

**Issue by jensenbox** [GreenmaskIO/greenmask#142]
Would be nice to be able to delete all dumps older than a certain date or more importantly, delete all except the most recent N dumps.

**Comment by wwoytenko** [comment]
Hi! Noted. I will implement it in 2024 Q3

**Comment by wwoytenko** [comment]
Hi! @jensenbox 
Dump retention management is implemented now by #201

The expected release date is between 1 - 10 October 2024. But you can build the binary from the main branch.

Regards
