### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by 0dragosh** [GreenmaskIO/greenmask#151]
It would be great if greenmask were also released as a minimal container image, preferably hosted on GitHub’s feee container registry ghcr.io.

**Comment by wwoytenko** [comment]
Hi! Thank you for your message. Could you please clarify what should be included in the lightweight container? Are you suggesting using Alpine? Also, could you explain why you prefer GitHub Registry over Docker Hub?

Thank you.

**Comment by 0dragosh** [comment]
Hello! I couldn't find a container image for greenmask in the documentation, maybe there is one and I'm just unaware? Sorry for not starting with that.

As for what should be in the image just what the application needs and the binary itself I guess. Alpine is fine, or just starting from the regular upstream go container.

The reason I suggested GHCR as opposed to Docker Hub [rate limits everyone](https://docs.docker.com/docker-hub/download-rate-limit/) while GitHub's free container registry does not. For open source projects like this it's very easy to just use ghcr.io.

**Comment by wwoytenko** [comment]
Thank you for the clarification. I've noted the information about the GitHub registry, and we might consider publishing builds there as well.

>  I couldn't find a container image for greenmask in the documentation

Yes, you're correct—there's no information on the Installation page I will fix it. However, the image already exists and can be found on Docker Hub:
[Greenmask Docker Image](https://hub.docker.com/r/greenmask/greenmask)

> Alpine is fine

Noted as well.


Thanks!

**Comment by sraka1** [comment]
@wwoytenko the Docker image seems very out of date (3mo old), as does the latest release in GH releases? Any plans for a new release with the subset changes?

**Comment by wwoytenko** [comment]
@sraka1
The v0.2b2 version, incorporating the latest changes (including subset), is scheduled for release at the end of August, approximately between the 29th and 30th.

**Comment by wwoytenko** [comment]
@sraka1 the v0.2.0b2 was published, so the latest version of a container is available

**Comment by wwoytenko** [comment]
@0dragosh, the images have been published on ghcr.io
