### ISSUE TITLE
Disabling foreign keys on AWS RDS.

### ISSUE THREAD

**Issue by N-Putting** [GreenmaskIO/greenmask#228]
As RDS does not support `--disable-triggers` is there any way to use `set session_replication_role = replica;` to disable it for each session? I tried it with a before and after data script but it won't work for jobs as it would need to run for each. 

Here is an example how pgsync did it with another option. https://github.com/ankane/pgsync/commit/88d17cd8ca3c5cad78062b6520df228aaaa119ef

**Comment by wwoytenko** [comment]
Hi! This will require a small code change, and I should be able to publish it this week. It looks like --disable-triggers might not be functioning correctly at the moment either. I’ll keep you posted.

**Comment by N-Putting** [comment]
Any update on this?

**Comment by wwoytenko** [comment]
@N-Putting 
It is in progress. We aim to publish before new year.

**Comment by wwoytenko** [comment]
#252 is merged

**Comment by wwoytenko** [comment]
@N-Putting let me know if it solves your request. Thanks in advance
