### ISSUE TITLE
bug: GetRawColumnValue is not working in TemplateRecord transformers

### ISSUE THREAD

**Issue by janmeier** [GreenmaskIO/greenmask#239]
It seems the `GetRawColumnValue` and `SetRawColumnValue` helpers are not available in the context of the `TemplateRecord` transformer.

`error="data stage dumping error: at least one worker exited with error: error processing table dump public.orders: dump error: dump error on table public.orders at line 1: dump error on table public.orders at line 1: error executing template: template: tmpl:1:11: executing \"tmpl\" at <.GetRawColumnValue>: can't evaluate field GetRawColumnValue in type *toolkit.RecordContext" pid=17362`

This regression has appeared in `v2.1.0`

**Comment by wwoytenko** [comment]
Thank you. I will resolve this issue ASAP.

**Comment by wwoytenko** [comment]
#242 will close this issue

**Comment by wwoytenko** [comment]
Published in v0.2.3
