### ISSUE TITLE
greenmask restore fails without error messages or exiting

### ISSUE THREAD

**Issue by jeffsutherland-bluesky** [GreenmaskIO/greenmask#28]
I am running `greenmask restore --config config.yml`, and it is failing after an hour or so of restoring a 70 GB database. It stops running, but it does not exit, and does not display any error messages. I know it has stopped working because htop no longer shows the process.

Here are my specs:

* greenmask 0.1.6
* t2.micro EC2 instance
* Amazon Linux 2023
* 1 CPU, 1 GB RAM
* 60 GB storage
* RDS Aurora Postgres DB
* DB size is 70 GB (14.5 GB compressed)

How do I get greenmask to finish?

**Comment by wwoytenko** [comment]
Hi! 

Could you provide the Greenmask version? Are you using S3 storage or directory?


Try to execute Greenmask in debug mode. Maybe you will find something that you can share.

Let's gather more information

**Comment by jeffsutherland-bluesky** [comment]
I am using v0.1.6. The storage is a directory. I ran greenmask restore in debug mode. Once again, it stopped working, with no exit and no error-level logs. It stops with the following debug message:

```
2024-03-14T17:46:57Z DBG ../greenmask/internal/db/postgres/pgrestore/pgrestore.go:44 > pg_restore: /usr/local/pgsql/bin/pg_restore --dbname host=db.host.name port=5432 user=postgres dbname=db_name password=super_secret_password --jobs 1 --section post-data --username postgres /tmp/1710436063879645860
 pid=145520
```

**Comment by wwoytenko** [comment]
Try to restore dump directly via pg_reatore

'pg_restore -U postgres -h localhost --jobs 10 /storage_path/1708598401362987000'

Replace your connection string and actual backup id (1708598401362987000)

In case it will stop unexpectedly, there is going to be bug in ported library.

**Comment by wwoytenko** [comment]
I suspect there is bug in TOC library. Add --verbose parameter in pg_restore command

**Comment by wwoytenko** [comment]
Provide PostgreSQL version as well, please

**Comment by jeffsutherland-bluesky** [comment]
I ran pg_restore as directed. No errors, and it exited as expected.

I am using Postgres 13.13.

**Comment by wwoytenko** [comment]
Does Greenmask return non zero exit code?

Seems I suspect it is a schema restoration issue, could two times run Greenmask with next parameters:

1. greenmask --config config.yml restore --schema-only --verbose
2. greenmask --config config.yml restore --verbose

The things that I want you to provide:

- is the schema and data restored in database (even partially if greenmask fails)?
- is Greenmask fails on the index or constraint restoration?
- could you check the PostgreSQL log as well, maybe there you will find log like with the reason?

**Comment by jeffsutherland-bluesky** [comment]
I get the following with verbose flag enabled:

```
$ greenmask --config config.yml restore --schema-only --verbose latest
{"level":"fatal","error":"1 error(s) decoding:\n\n* cannot parse 'restore.pg_restore_options.schema-only' as bool: strconv.ParseBool: parsing \"--verbose\": invalid syntax","time":"2024-03-15T17:55:14Z"}
```

**Comment by jeffsutherland-bluesky** [comment]
I am also getting the following with just --schema-only enabled, but not --verbose:

```
$ greenmask --config config.yml restore --schema-only latest
{"level":"fatal","error":"1 error(s) decoding:\n\n* cannot parse 'restore.pg_restore_options.schema-only' as bool: strconv.ParseBool: parsing \"latest\": invalid syntax","time":"2024-03-15T18:00:24Z"}
```

**Comment by wwoytenko** [comment]
That's my fault. Try to use

`greenmask --config config.yml restore --verbose=true --schema-only=true latest`

**Comment by jeffsutherland-bluesky** [comment]
Your first command ran with no issues. So did your second command, except that it took forever to restore the indexes. Maybe restoring indexes was where it stopped working before?

**Comment by wwoytenko** [comment]
Thank you for the details. I was not able to reproduce your case.

Could you try to restore the DB with two steps:

- `greenmask --config config.yml restore --schema-only=true --verbose=true latest --log-level=debug`
- `greenmask --config config.yml restore --data-only=true --verbose=true latest --log-level=debug`

This command splits the restoration into two stages:
- Schema will be restored in the first command. Grenmask internally delegates it to pg_restore
- The data will be restored in the second command. Greenmask restores the data by itself

If there is a stuck in the second command It is supposed to be a bug in data restoration.

**Comment by wwoytenko** [comment]
@jeffsutherland-bluesky has this problem been solved? I could not reproduce your case
