### ISSUE TITLE
Env var values not being loaded without a config file definition

### ISSUE THREAD

**Issue by joao-zanutto** [GreenmaskIO/greenmask#48]
@wwoytenko I encountered a problem where environment variables are not being loaded if their config isn't defined in a config file. It seems that this is a known Viper issue: https://github.com/spf13/viper/issues/584

I'll come up with a PR to solve this issue, changing the `common.tmp_dir` default definition.

We can also utilize this PR to set a default behavior for `storage` config. I see these possible scenarios
- Define default storage to directory storage on `~/dumps` -- this would allow Docker users to map a volume to `/home/greenmask/dumps` and use it without needing to specify the `storage.directory.path` configuration
- Require storage configuration and error out in case none is provided

**Comment by wwoytenko** [comment]
@joao-zanutto thank you for your research. You're right. We can overcome this issue by manually registering ENV vars. It is completed in #51 . Rebase from the actual main branch and adapt your PR #49 last changes. 

About the next points 

> Define default storage to directory storage on ~/dumps -- this would allow Docker users to map a volume to /home/greenmask/dumps and use it without needing to specify the storage.directory.path configuration

Agree. You can add it into #49 

> Require storage configuration and error out in case none is provided

Looks like I have done it in #51

**Comment by joao-zanutto** [comment]
@wwoytenko following your implementation we would need to statically bind each env to have it work, I tried a few solution, (like the one described in this comment https://github.com/spf13/viper/issues/584#issuecomment-1210957041) but ended up finding a new build flag we can add to make it work out of the box.

There is a new private function `bindStruct()` that is being called inside the `Unmarshall()` function, but since it has some retrocompability issues, it was put behind this `-tags=viper_bind_struct` build arg. (See https://github.com/spf13/viper/pull/1429)

I already built and test locally and it is working, however it doesn't work for the S3 storage parameters because it's defined as a pointer and the function can't parse it properly (See https://github.com/spf13/viper/pull/1429#issuecomment-1856118406). Is there a chance we can remove the pointer definition se we don't have to statically define each S3 parameter as its own env and bind them individually?

**Comment by wwoytenko** [comment]
I think you can easily get rid of the pointers. It should work as expected, verify that all is okay and NewConfig function calls correctly

**Comment by wwoytenko** [comment]
Leave a comment in the code and Makefile as well so we would determine why it uses build flags

**Comment by joao-zanutto** [comment]
> I think you can easily get rid of the pointers. It should work as expected, verify that all is okay and NewConfig function calls correctly

I did as you instructed but may have missed something because I cannot make it work correctly and I'm having difficult troubleshooting it. May I have your assistance in #55 ?
